export enum TransactionType {
  DEPLOY_CONTRACT = 'DEPLOY_CONTRACT',
  ADD_LIQUIDITY = 'ADD_LIQUIDITY',
  REMOVE_LIQUIDITY = 'REMOVE_LIQUIDITY',
  SWAP = 'SWAP',
  MM_SWAP = 'MM_SWAP',
}

export enum SwapSettingType {
  QUICK_SELL = 'QUICK_SELL',
  QUICK_BUY = 'QUICK_BUY',
  QUICK_SWAP = 'QUICK_SWAP',
  KEEP_TARGET_PRICE = 'KEEP_TARGET_PRICE',
  KEEP_TARGET_VOLUME = 'KEEP_TARGET_VOLUME',
}
